name: Jest
on:
  workflow_call:
    inputs:
      extensionName:
        required: true
        type: string
      heyframeVersion:
        required: false
        type: string
        default: ".auto"
      heyframeVersionFallback:
        required: false
        type: string
        default: trunk
      heyframe-repository:
        type: string
        default: heyframe/heyframe
      composerRootVersion:
        required: false
        type: string
        default: ".auto"

jobs:
  run:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Setup Extension
        uses: heyframe/github-actions/setup-extension@main
        with:
          heyframeVersion: ${{ inputs.heyframeVersion }}
          heyframeVersionFallback: ${{ inputs.heyframeVersionFallback }}
          heyframe-repository: ${{ inputs.heyframe-repository }}
          extensionName: ${{ github.event.repository.name }}
          composerRootVersion: ${{ inputs.composerRootVersion }}
          install: true
          install-admin: true
          env: prod
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              }
            }

      - name: Jest Unit Tests
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run unit -- --coverage